### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rndmh3ro** [nmeisenzahl/hijack-kubernetes#2]
I saw your talk at the devopscon and really liked it!
I thought about doing something similar at my company for internal teaching, so I'd love to know what kind of license the code and slides have?

**Comment by nmeisenzahl** [comment]
Hi @rndmh3ro sorry for my late response. I had some days off. Also thanks for making me aware of the missing license. I added it (MIT) some seconds ago.
Let me know in case you need further details.

**Comment by rndmh3ro** [comment]
Thank you!
